/**
 * A hand-picked emoji set — the ones people actually reach for in a chat.
 *
 * Authored as `"<char> <keyword> <keyword>…"` lines because a full object per
 * emoji would triple the file for no gain. The first keyword doubles as the
 * display name, so put the obvious word first.
 */

export interface Emoji {
  char: string;
  keywords: string[];
}

export interface EmojiGroup {
  name: string;
  emoji: Emoji[];
}

function group(name: string, entries: string[]): EmojiGroup {
  return {
    name,
    emoji: entries.map((entry) => {
      const [char, ...keywords] = entry.split(' ');
      return { char, keywords };
    }),
  };
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  group('Smileys', [
    '😀 grinning grin happy',
    '😄 smile joy',
    '😁 beaming grin',
    '😆 laughing satisfied',
    '😅 sweat nervous laugh',
    '🤣 rofl rolling laughing',
    '😂 joy tears laughing',
    '🙂 slight smile',
    '🙃 upside-down silly',
    '😉 wink flirt',
    '😊 blush smile',
    '😇 innocent halo',
    '🥰 adore hearts love',
    '😍 heart-eyes love',
    '🤩 star-struck amazed',
    '😘 kiss blow',
    '🥲 tearful smile',
    '😋 yum tasty',
    '😛 tongue cheeky',
    '😜 winking-tongue joking',
    '🤪 zany goofy',
    '🤑 money-mouth rich',
    '🤗 hugging hug',
    '🤭 oops giggle',
    '🤫 shush quiet',
    '🤔 thinking hmm',
    '🫡 salute yes',
    '🤐 zipped secret',
    '🤨 raised-eyebrow suspicious',
    '😐 neutral blank',
    '😑 expressionless',
    '😶 speechless silence',
    '😏 smirk sly',
    '😒 unamused meh',
    '🙄 eye-roll',
    '😬 grimace awkward',
    '😌 relieved calm',
    '😔 pensive sad',
    '😴 sleeping zzz',
    '😷 mask sick',
    '🤒 fever ill',
    '🤕 injured bandage',
    '🥵 hot overheated',
    '🥶 freezing cold',
    '🥴 woozy tipsy',
    '😵 dizzy knocked-out',
    '🤯 mind-blown shocked',
    '🤠 cowboy',
    '🥳 partying celebrate',
    '😎 sunglasses cool',
    '🤓 nerd geek',
    '🧐 monocle inspect',
    '🙁 frowning',
    '😮 surprised wow',
    '😲 astonished shock',
    '😳 flushed embarrassed',
    '🥺 pleading puppy',
    '🥹 holding-back-tears touched',
    '😨 fearful scared',
    '😰 anxious sweat',
    '😢 crying sad',
    '😭 sobbing crying',
    '😱 screaming fear',
    '😞 disappointed',
    '😫 tired',
    '🥱 yawning bored',
    '😤 triumph huff',
    '😡 rage angry',
    '😠 angry mad',
    '🤬 cursing swearing',
    '😈 devil mischief',
    '💀 skull dead',
    '💩 poop',
    '🤡 clown',
    '👻 ghost boo',
    '👽 alien',
    '🤖 robot bot',
  ]),

  group('Gestures', [
    '👍 thumbs-up yes like',
    '👎 thumbs-down no dislike',
    '👌 ok perfect',
    '🤌 pinched-fingers italian',
    '🤏 pinch small',
    '✌️ peace victory',
    '🤞 fingers-crossed luck',
    '🤟 love-you',
    '🤘 rock horns',
    '🤙 call-me shaka',
    '👈 point-left',
    '👉 point-right',
    '👆 point-up',
    '👇 point-down',
    '☝️ index-up one',
    '✋ raised-hand stop',
    '👋 wave hello bye',
    '🤝 handshake deal',
    '🙏 pray thanks please',
    '✊ fist raised',
    '👊 fist-bump punch',
    '👏 clap applause',
    '🙌 raised-hands praise',
    '👐 open-hands',
    '🤲 palms-up',
    '🫶 heart-hands love',
    '💪 muscle strong flex',
    '✍️ writing hand',
    '🤳 selfie',
  ]),

  group('People', [
    '👶 baby',
    '🧒 child kid',
    '🧑 person adult',
    '👨 man',
    '👩 woman',
    '🧔 beard bearded',
    '👴 old-man grandpa',
    '👵 old-woman grandma',
    '👮 police cop',
    '🕵️ detective spy',
    '👷 builder construction',
    '👸 princess',
    '🦸 superhero hero',
    '🦹 supervillain villain',
    '🧙 wizard mage',
    '🎅 santa christmas',
    '🙋 raising-hand question',
    '🙆 gesturing-ok yes',
    '🙅 gesturing-no stop',
    '🤷 shrug dunno',
    '🤦 facepalm ugh',
    '💁 tipping-hand sassy',
    '🙇 bowing sorry',
    '💃 dancer dancing',
    '🕺 dancing-man',
    '👫 couple holding-hands',
    '👪 family',
    '🫂 hug people',
  ]),

  group('Animals', [
    '🐶 dog puppy',
    '🐱 cat kitten',
    '🐭 mouse',
    '🐰 rabbit bunny',
    '🦊 fox',
    '🐻 bear',
    '🐼 panda',
    '🐨 koala',
    '🐯 tiger',
    '🦁 lion',
    '🐮 cow',
    '🐷 pig',
    '🐸 frog',
    '🐵 monkey',
    '🙈 see-no-evil monkey',
    '🙉 hear-no-evil monkey',
    '🙊 speak-no-evil monkey',
    '🐔 chicken',
    '🐧 penguin',
    '🐦 bird',
    '🐤 chick',
    '🦉 owl',
    '🐺 wolf',
    '🐴 horse',
    '🦄 unicorn',
    '🐝 bee',
    '🐛 bug caterpillar',
    '🦋 butterfly',
    '🐌 snail slow',
    '🐢 turtle',
    '🐍 snake',
    '🐙 octopus',
    '🐬 dolphin',
    '🐳 whale',
    '🦈 shark',
    '🐘 elephant',
    '🌵 cactus',
    '🌲 tree evergreen',
    '🌱 seedling plant',
    '🍀 clover luck',
    '🍁 maple-leaf autumn',
    '🌸 blossom flower',
    '🌹 rose flower',
    '🌻 sunflower',
  ]),

  group('Food', [
    '🍎 apple',
    '🍊 orange tangerine',
    '🍋 lemon',
    '🍌 banana',
    '🍉 watermelon',
    '🍇 grapes',
    '🍓 strawberry',
    '🍒 cherries',
    '🍑 peach',
    '🥭 mango',
    '🍍 pineapple',
    '🍅 tomato',
    '🥑 avocado',
    '🥕 carrot',
    '🌽 corn',
    '🍞 bread',
    '🧀 cheese',
    '🥚 egg',
    '🍳 cooking frying',
    '🥞 pancakes',
    '🍔 burger',
    '🍟 fries chips',
    '🍕 pizza',
    '🌭 hot-dog',
    '🥪 sandwich',
    '🌮 taco',
    '🥗 salad',
    '🍝 pasta spaghetti',
    '🍜 ramen noodles',
    '🍣 sushi',
    '🍦 ice-cream',
    '🍩 doughnut donut',
    '🍪 cookie biscuit',
    '🎂 birthday-cake',
    '🍰 cake slice',
    '🧁 cupcake',
    '🍫 chocolate',
    '🍿 popcorn',
    '☕ coffee',
    '🍵 tea',
    '🧋 bubble-tea boba',
    '🥤 soda drink',
    '🍺 beer',
    '🍻 cheers beers',
    '🍷 wine',
    '🥂 champagne clink',
    '🍸 cocktail',
  ]),

  group('Activities', [
    '⚽ football soccer',
    '🏀 basketball',
    '🏈 american-football',
    '⚾ baseball',
    '🎾 tennis',
    '🏐 volleyball',
    '🎱 pool billiards',
    '🏓 ping-pong',
    '🏒 hockey',
    '⛳ golf',
    '🏹 archery bow',
    '🎣 fishing',
    '🥊 boxing glove',
    '🎿 skiing',
    '🏂 snowboarding',
    '🏋️ lifting gym workout',
    '🏊 swimming',
    '🚴 cycling bike',
    '🏆 trophy win',
    '🥇 gold first',
    '🥈 silver second',
    '🥉 bronze third',
    '🎯 bullseye target',
    '🎮 gaming controller',
    '🕹️ joystick arcade',
    '🎲 dice game',
    '🧩 puzzle piece',
    '🎨 art palette',
    '🎭 theatre masks',
    '🎤 microphone sing',
    '🎧 headphones music',
    '🎸 guitar',
    '🎹 piano keys',
    '🥁 drum',
    '🎬 clapper film',
    '🎉 party popper',
    '🎊 confetti',
    '🎈 balloon',
    '🎁 gift present',
  ]),

  group('Travel', [
    '🚗 car',
    '🚕 taxi',
    '🚌 bus',
    '🚓 police-car',
    '🏎️ racing-car',
    '🏍️ motorcycle',
    '🚲 bicycle bike',
    '🚂 train locomotive',
    '🚇 metro subway',
    '🚁 helicopter',
    '✈️ aeroplane flight',
    '🚀 rocket launch',
    '🛸 ufo saucer',
    '⛵ sailboat',
    '⚓ anchor',
    '🗺️ map',
    '🏔️ mountain peak',
    '🌋 volcano',
    '🏕️ camping tent',
    '🏖️ beach',
    '🏝️ island',
    '🏡 home house',
    '🏢 office building',
    '🏥 hospital',
    '🏫 school',
    '🏰 castle',
    '🌃 night city',
    '🌆 cityscape dusk',
    '🌍 earth globe world',
    '🌙 moon crescent',
    '⭐ star',
    '🌟 sparkle glowing',
    '✨ sparkles magic',
    '⚡ lightning zap',
    '🔥 fire lit',
    '🌈 rainbow',
    '☀️ sun sunny',
    '⛅ cloudy sun',
    '☁️ cloud',
    '🌧️ rain',
    '❄️ snowflake cold',
    '🌊 wave ocean',
  ]),

  group('Objects', [
    '⌚ watch',
    '📱 phone mobile',
    '💻 laptop computer',
    '🖥️ desktop monitor',
    '⌨️ keyboard typing',
    '💾 floppy save',
    '📷 camera photo',
    '🔍 magnifier search',
    '💡 bulb idea',
    '🔦 torch flashlight',
    '🔋 battery',
    '🔌 plug power',
    '📞 telephone call',
    '📺 tv television',
    '⏰ alarm clock',
    '⏳ hourglass waiting',
    '💰 money bag',
    '💵 cash dollar',
    '💳 card credit',
    '💎 gem diamond',
    '🔧 spanner wrench',
    '🔨 hammer',
    '⚙️ gear settings',
    '🧪 test-tube science',
    '🔬 microscope',
    '💊 pill medicine',
    '🛏️ bed sleep',
    '🔑 key',
    '🔒 lock locked',
    '🔓 unlocked open',
    '📦 package box',
    '✉️ envelope email',
    '📝 memo note',
    '📄 document page',
    '📚 books library',
    '📖 book reading',
    '📅 calendar date',
    '📌 pin pushpin',
    '📎 paperclip attach',
    '✂️ scissors cut',
    '✏️ pencil write',
    '📊 bar-chart stats',
    '📈 chart-up growth',
    '📉 chart-down decline',
    '🗑️ bin trash delete',
  ]),

  group('Symbols', [
    '❤️ red-heart love',
    '🧡 orange-heart',
    '💛 yellow-heart',
    '💚 green-heart',
    '💙 blue-heart',
    '💜 purple-heart',
    '🖤 black-heart',
    '🤍 white-heart',
    '💔 broken-heart',
    '💕 two-hearts love',
    '💖 sparkling-heart',
    '💯 hundred perfect',
    '💥 boom collision',
    '💫 dizzy stars',
    '💦 sweat droplets',
    '💨 dash wind',
    '💬 speech comment',
    '💭 thought bubble',
    '💤 zzz sleeping',
    '✅ tick check done',
    '❌ cross wrong',
    '⭕ circle red',
    '⚠️ warning caution',
    '🚫 forbidden no',
    '❗ exclamation',
    '❓ question',
    '🔴 red-circle',
    '🟡 yellow-circle',
    '🟢 green-circle',
    '🔵 blue-circle',
    '♻️ recycle',
    '🔔 bell notification',
    '🔕 muted bell',
    '🔊 speaker loud',
    '🔇 mute silent',
    '➕ plus add',
    '➖ minus subtract',
    '♾️ infinity forever',
    '🔗 link chain',
    '📍 location pin',
    '🎵 music note',
    '🎶 music notes',
  ]),
];

/** The six one-tap reactions offered on a message. */
export const QUICK_REACTIONS: string[] = ['👍', '❤️', '😂', '😮', '😢', '🙏'];

const ALL_EMOJI: Emoji[] = EMOJI_GROUPS.flatMap((entry) => entry.emoji);

const NAMES = new Map(ALL_EMOJI.map((entry) => [entry.char, entry.keywords[0] ?? '']));

/** The leading keyword, tidied for display — `''` for anything not in the set. */
export function emojiName(char: string): string {
  return (NAMES.get(char) ?? '').replace(/-/g, ' ');
}

/**
 * Keyword search. A keyword that *starts* with the term outranks one that
 * merely contains it, so "car" leads with 🚗 rather than 🃏.
 */
export function searchEmoji(term: string, limit = 48): string[] {
  const query = term.trim().toLowerCase();
  if (!query) return [];

  const leading: string[] = [];
  const trailing: string[] = [];

  for (const entry of ALL_EMOJI) {
    if (entry.keywords.some((keyword) => keyword.startsWith(query))) {
      leading.push(entry.char);
      if (leading.length >= limit) break;
    } else if (entry.keywords.some((keyword) => keyword.includes(query))) {
      trailing.push(entry.char);
    }
  }

  return leading.concat(trailing).slice(0, limit);
}
